# Generated by Django 3.0.5 on 2020-04-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponsOjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('end_data', models.DateField()),
                ('summary', models.CharField(max_length=120)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories')),
            ],
        ),
    ]
