# Generated by Django 3.0.5 on 2020-04-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_couponsojects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponsojects',
            old_name='price',
            new_name='price_sail',
        ),
        migrations.AddField(
            model_name='categories',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponsojects',
            name='price_service',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
