# Generated by Django 3.0.5 on 2020-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200424_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsojects',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
