# Generated by Django 3.0.5 on 2020-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_couponsojects_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsojects',
            name='photo',
            field=models.ImageField(default='backCoupons/coupon-img.png', upload_to=''),
        ),
    ]
